version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app  # ソースコードをマウントして変更を即反映
      - ~/.gradle:/home/gradle/.gradle # Gradleキャッシュ（ビルド高速化）
    environment:
      - SPRING_DEVTOOLS_REMOTE_SECRET=secret
      - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
    restart: no
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
